version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 8067:5000
    env_file:
      - ./.env.dev
  db:
    build: ./services/postgres
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    ports:
      - 12347:5432

volumes:
  postgres_data:
